include: package:flutter_lints/flutter.yaml

# Additional lint rules for this project
linter:
  rules:
    # Style
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    
    # Documentation
    public_member_api_docs: false
    
    # General
    avoid_print: true
    prefer_typing_uninitialized_variables: true
    
    # Errors
    avoid_returning_null_for_void: true
    cancel_subscriptions: true
    close_sinks: true
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
  language:
    strict-raw-types: true
